# Generated by Django 5.2 on 2025-04-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=500)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('smoke_habits', models.CharField(max_length=35, null=True)),
                ('alcohol_habits', models.CharField(max_length=35, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('verified', models.CharField(default=False, max_length=30, null=True)),
                ('dob', models.DateTimeField(null=True)),
            ],
        ),
    ]
